### ISSUE TITLE
Build failing with latest vulkan beta - 455.50.02

### ISSUE THREAD

**Issue by abhishek-rawal** [Frogging-Family/nvidia-all#27] opened 2021-01-21 03:33 UTC
Hello,
I manually updated customization.cfg with `_driver_branch="vulkandev"` and `_driver_version="455.50.02"`. Below is the error I receive after executing `makepkg -si`

```
-> Applying linux-version.diff for 5.10.3-106-tkg-upds...
patching file nvidia-drm/nvidia-drm-gem-nvkms-memory.c
patching file nvidia-drm/nvidia-drm-encoder.c
patching file nvidia-drm/nvidia-drm-drv.c
patching file nvidia-drm/nvidia-drm-connector.c
patching file common/inc/nv.h
Hunk #1 succeeded at 36 with fuzz 2 (offset 18 lines).
patching file nvidia-drm/nvidia-drm-gem.h
Hunk #1 succeeded at 45 with fuzz 1 (offset 7 lines).
patching file nvidia-drm/nvidia-drm-helper.c
Hunk #1 succeeded at 29 with fuzz 1.
patching file nvidia-drm/nvidia-drm-linux.c
patching file nvidia-uvm/uvm_linux.h
patching file nvidia/nvlink_linux.c
Hunk #1 succeeded at 39 with fuzz 1 (offset 2 lines).
patching file nvidia/os-interface.c
Hunk #1 succeeded at 24 with fuzz 2 (offset 10 lines).
patching file nvidia-modeset/nvidia-modeset-linux.c
  -> Applying 455 crashfix for 5.10.3-106-tkg-upds...
patching file nvidia-modeset/nvidia-modeset-linux.c
Hunk #1 succeeded at 23 (offset 2 lines).
Hunk #2 FAILED at 171.
Hunk #3 succeeded at 314 with fuzz 1 (offset 115 lines).
1 out of 3 hunks FAILED -- saving rejects to file nvidia-modeset/nvidia-modeset-linux.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done
```

Can someone please help me to fix this ?

**Comment by Tk-Glitch** [comment] 2021-01-21 12:52
The issue is fixed with https://github.com/Frogging-Family/nvidia-all/commit/d27b60d5cba222ed1fd11a002a383fddef7720f5

The patch that failed to apply was a hotfix for the upstream problem reported [here](https://forums.developer.nvidia.com/t/455-23-04-page-allocation-failure-in-kernel-module-at-random-points/155250/95). I'm not sure yet that patch is still needed on 455.50.02 after checking the code out, so I have decided to skip applying the patch for now. If you experience the issue reported in the thread above while using 455.50.02, please give us feedback about it either here or in a new issue.

Thank you!

**Closed by Tk-Glitch** 2021-01-21 12:52 UTC
